section products test
KR2504/web-project-team-13 pull request #11
Opened 2022-01-14 23:50 UTC by SHEVEL0V

тестовая версия. пока нет картинок.

2022-01-15 13:22 UTC, KR2504 requested changes
Вроде всё четко, единственно добавили миксины для фонтов, может всё с ними сделаешь, если где-то letter spacing нет, по макету, всё равно ставь 0.4

2022-01-15 13:22 UTC, KR2504 commented on src/partials/products.html
> +<section class="container products">
сделай див для контейнера отдельный

2022-01-15 15:46 UTC, SHEVEL0V commented on src/partials/products.html
> +<section class="container products">
Ok

2022-01-16 10:12 UTC, KR2504 approved these changes

2022-01-16 10:13 UTC, merged