summary footer 320
KR2504/web-project-team-13 pull request #7
Opened 2022-01-14 16:49 UTC by Vitalii-Malintsov

Внесены HTML and SASS

2022-01-14 17:12 UTC, KR2504 requested changes

2022-01-14 17:12 UTC, KR2504 commented on src/partials/footer.html
> +    <div class="footer__rights">
footer-rights

2022-01-14 17:12 UTC, KR2504 commented on src/partials/footer.html
> +      <p class="footer__rights--text"><span>&#169;</span>2022 - IceCream. All Rights Reserved.</p>
footer-rights__text

2022-01-14 17:12 UTC, KR2504 commented on src/sass/layout/_footer.scss
> +  font-family: 'DM Sans';
DM Sans не пиши, он как основной в боди

2022-01-14 17:12 UTC, KR2504 commented on src/sass/layout/_footer.scss
> +  font-weight: bold;
прописывай цифрами `700`

2022-01-14 17:12 UTC, KR2504 commented on src/partials/footer.html
> +    <div class="footer__link">
footer__connect

2022-01-15 11:38 UTC, Vitalii-Malintsov commented on src/sass/layout/_footer.scss
> +  font-family: 'DM Sans';
DM Sans не подтягивает с body

2022-01-15 11:41 UTC, Vitalii-Malintsov commented on src/partials/footer.html
> +      <li class="footer__social--icon">
Исправил

2022-01-15 11:41 UTC, Vitalii-Malintsov commented on src/partials/footer.html
> +        <a href="https://github.com/" class="footer__social--link">
Исправил

2022-01-15 11:41 UTC, Vitalii-Malintsov commented on src/partials/footer.html
> +      <a href="tel:+610383766284" class="footer__link--tel">
Исправил

2022-01-15 11:41 UTC, Vitalii-Malintsov commented on src/partials/footer.html
> +    <div class="footer__rights">
Исправил

2022-01-15 11:41 UTC, Vitalii-Malintsov commented on src/partials/footer.html
> +      <p class="footer__rights--text"><span>&#169;</span>2022 - IceCream. All Rights Reserved.</p>
Исправил

2022-01-15 11:41 UTC, Vitalii-Malintsov commented on src/sass/layout/_footer.scss
> +  font-weight: bold;
Исправил

2022-01-15 11:41 UTC, Vitalii-Malintsov commented on src/partials/footer.html
> +    <div class="footer__link">
Исправил

2022-01-15 11:43 UTC, Vitalii-Malintsov commented
Внесены исправления.

2022-01-15 11:43 UTC, closed without merging

2022-01-15 15:20 UTC, KR2504 reviewed
Гуд